function res = isEqualTol(argument1, argument2, context, toleranceInput)
  if (nargin == 3),
    res = CompareData(argument1, argument2, context, ...
            struct('displaycontextprogress', 0, 'NumericTolerance', 0, ...
            'showMinMaxAbsDiff', 0));
  else
    res = CompareData(argument1, argument2, context, ...
            struct('displaycontextprogress', 0, 'NumericTolerance', toleranceInput, ...
            'showMinMaxAbsDiff', 0));
  end
end